Call sqlite3_reset after sqlite3_step
Fixes issue where new data does not correctly bind to a prepared statement after the first execution when inserting records, causing an unique constraint exception:

Error: Exception in HostFunction: [op-sqlite] SQLite code: 19 execution error: UNIQUE constraint failed: mytable.id